title: magchoの雑記
subtitle: magchoのなんでもブログ
repository: magcho/jekyll-penguin
author: magcho
branch: master
twitter:
  username: magcho0527
descprition: >
  ペンギンが好き

baseurl: "https://blog.magcho.com"
url: "https://blog.magcho.com"

author:
  name: magcho
  email: mail@magcho.com
  github: magcho
  twitter: magcho0527

permalink: "/:year/:i_month/:i_day/:title/"

timezone: Asia/Tokyo
future: false

# paginate: 3
# paginate_path: "page:num"

sass:
  style: expanded  #整形
  sass_dir: _sass
  # style: compressed   #圧縮


exclude:
  - .pug-backup
  - vendor
  - Gemfile
  - Gemfile.lock


plugins:
  - jekyll-gist
  - jekyll-paginate-v2

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  permalink: '/page/:num/'
  # title_suffix: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
