title: magchoの雑記
descprition: >
  ペンギンが好き

baseurl: ""
url: "https://blog.magcho.com"

author:
  name: magcho
  email: mail@magcho.com
  github: magcho
  twitter: magcho0527

# paginate: 3
# paginate_path: "page:num"

sass:
  style: expanded  #整形
  sass_dir: _sass
  # style: compressed   #圧縮


gem:
  - jekyll-feed

plugins:
  # - jekyll-paginate
  # - jekyll-feed
  - jekyll-pug
